import "~/styles/globals.css";
import { UserContextProvider } from "~/context/userContext";
import { ThemeProvider } from "~/components/theme-provider";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Header from "~/components/Header";
import { getServerSession } from "next-auth";
import { authOptions } from "~/server/auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`font-sans ${inter.variable} pt-[50px]`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UserContextProvider initialUser={session?.user}>
            <Header />
            {children}
          </UserContextProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
